language: python
python: 2.7
services: postgresql
env: DJANGO=1.8.5
before_install:
  - export DJANGO_SETTINGS_MODULE=readbin.settings.test
  - export PYTHONPATH=$HOME/builds/asnelzin/readbin
install:
  - pip install -r requirements/base.txt
before_script:
  - psql -U postgres -c "CREATE DATABASE readbin;"
script:
  - python manage.py test tests